### ISSUE TITLE
I get error related to &UGameInstanceMain::Get()->GetTimerManager()

### ISSUE THREAD

**Issue by YHSX88** [inanevin/UE4-Tween-Manager#1]
Hi

Not sure why but when using the code (via copy paste the 3 file fromt the repo) and compiling -> I get this error:
I'm pretty sure it's the way you named your GameInstance but even If it try with mine-> I get all sorts of other issues 

Can you please suggest any workaround

I'm using 4.27.2 -> Built from Source

Code:
![image](https://user-images.githubusercontent.com/16823745/152675136-b556bd33-65e8-4d7c-bd94-85a5fda4ff96.png)
Logs:
![image](https://user-images.githubusercontent.com/16823745/152675252-c24563a6-2fe0-4d80-9445-d4c3350c530f.png)

**Comment by inanevin** [comment]
The point of this call is to get the address of a timer manager instance while creating a CTween object. My Game Instance class has a static Get method, which returns the current alive instance of the game instance, which has a method GetTimerManager(), to return the world timer manager. Do you have such a game instance class, with Get() & GetTimerManager() methods defined?
